queue_rules:
  - name: default
    conditions:
      - check-success=commitlint
      - check-success=denolint
      - check-success=test (ubuntu-latest)
      - check-success=test (macos-latest)
      - check-success=test (windows-latest)

pull_request_rules:
  - name: Automatic merge of dependency updates
    conditions:
      - base=master
      - label=dependencies
    actions:
      queue:
        name: default
        method: squash
  - name: Delete branch after merge
    conditions:
      - merged
      - base=master
      - label=dependencies
    actions:
      delete_head_branch:
        force: false
