plugins:
  # Determine the type of release by analyzing commits.
  # ie: Major, Minor or Patch
  - "@semantic-release/commit-analyzer"

  # Generate CHANGELOG.md
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"

  # Commit CHANGELOG.md back to repo
  - - "@semantic-release/git"
    - assets: [CHANGELOG.md]
      message: "chore(release): update changelog [skip ci]"

  # Create new github release
  - "@semantic-release/github"
