version: '3'

silent: true

vars:
  UDD_VERSION: "0.5.0"
  DENO_INLINE_RUNNER: "deno run -qA --no-check -"

tasks:
  test:
    desc: Executes the test suite for this library
    cmds:
      - deno test -A --unstable --lock deps.lock.json lib/

  fmt:
    desc: Format JavaScript/TypeScript/JSON/Markdown files
    cmds:
      - deno fmt --ignore="node_modules,deps.lock.json,CHANGELOG.md"

  lint:
    desc: Lint JavaScript/TypeScript source code
    cmds:
      - deno lint --ignore="node_modules,deps.lock.json,udd.lock.json,CHANGELOG.md"

  update:
    desc: Updates all the things
    cmds:
      - echo "UPDATING task";
      - echo "--------------------------------------------------------------------------------";
      - task: updateTask
      - echo "";
      - echo "UPDATING deno";
      - echo "--------------------------------------------------------------------------------";
      - task: updateDeno
      - echo "";
      - echo "UPDATING nodejs";
      - echo "--------------------------------------------------------------------------------";
      - task: updateNodejs
      - echo "";
      - echo "UPDATING udd";
      - echo "--------------------------------------------------------------------------------";
      - task: updateUdd
      - echo "";
      - echo "UPDATING deno modules";
      - echo "--------------------------------------------------------------------------------";
      - task: updateDenoModules
      - echo "";
      - echo "UPDATING nodejs modules";
      - echo "--------------------------------------------------------------------------------";
      - task: updateNodejsModules

  updateTask:
    desc: Update the version of go-task as defined in .tool-versions
    cmds:
      - asdf plugin add task https://github.com/particledecay/asdf-task.git || true
      - asdf plugin update task
      - asdf install task latest
      - asdf local task latest

  updateDeno:
    desc: Update the version of deno as defined in .tool-versions
    cmds:
      - asdf plugin add deno https://github.com/asdf-community/asdf-deno.git || true
      - asdf plugin update deno
      - asdf install deno latest
      - asdf local deno latest

  updateNodejs:
    desc: Update the version of nodejs as defined in .tool-versions
    cmds:
      - asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git || true
      - asdf plugin update nodejs
      - asdf install nodejs latest
      - asdf local nodejs latest

  updateUdd:
    desc: Updates the version of the deno udd tool that we use
    vars:
      NEW_UDD_VERSION:
        sh: |
          echo 'console.log(
            (await fetch("https://deno.land/x/udd/main.ts")).url
              .split("@")[1]
              .split("/")[0]
          );' | {{.DENO_INLINE_RUNNER}}
    cmds:
      - echo "Upgrading udd from {{.UDD_VERSION}} to {{.NEW_UDD_VERSION}}";
      - |
        echo 'Deno.writeTextFileSync(
          "Taskfile.yml",
          Deno.readTextFileSync("Taskfile.yml").replace(
            "UDD_VERSION: \"{{.UDD_VERSION}}\"",
            "UDD_VERSION: \"{{.NEW_UDD_VERSION}}\"",
          ),
        );' | {{.DENO_INLINE_RUNNER}}
      - echo 'Deno.removeSync("udd.lock.json")' | {{.DENO_INLINE_RUNNER}} || true
      - deno cache --lock=udd.lock.json --lock-write https://deno.land/x/udd@{{.NEW_UDD_VERSION}}/main.ts

  updateDenoModules:
    desc: Updates all deno modules referenced in deps.ts with the udd tool
    cmds:
      - deno cache --lock=udd.lock.json https://deno.land/x/udd@{{.UDD_VERSION}}/main.ts
      - deno run -qA --lock=udd.lock.json --cached-only https://deno.land/x/udd@{{.UDD_VERSION}}/main.ts deps.ts
      - echo 'Deno.removeSync("deps.lock.json")' | {{.DENO_INLINE_RUNNER}} || true
      - deno cache --lock=deps.lock.json --lock-write deps.ts

  updateNodejsModules:
    desc: Updates all nodejs modules referenced in package.json with the npm tool
    cmds:
      - npm update
