on:
  pull_request:
    types:
      - opened
      - edited

env:
  CI: true

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
      - name: Get nodejs version
        run: echo ::set-output name=NODE_VERSION::$(cat .tool-versions | grep nodejs | xargs -n 1 | tail -n1)
        shell: bash
        id: nodev
      - name: Install nodejs
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ steps.nodev.outputs.NODE_VERSION }}
      - name: Restore nodejs cache
        uses: actions/cache@v2.1.6
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
          path: ~/.npm
      - name: Install node deps
        run: npm ci
      - name: Lint PR title & body.
        run: echo "${{ github.event.pull_request.title }}\n${{ github.event.pull_request.body }}" | npx commitlint
