on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  updatedeno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
      - name: Install the asdf tool version manager
        uses: asdf-vm/actions/install@v1.1.0
      - name: Update deno
        run: asdf install deno latest && asdf local deno latest
      - run: git status
