on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  updatedeno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: asdf-vm/actions/setup@v1.1.0
      - run: asdf plugin-add deno https://github.com/asdf-community/asdf-deno.git
      - run: echo ::set-output name=FROM_VERSION::$(asdf current deno | xargs -n 1 | sed -n '2p')
        id: from
      - run: asdf install deno latest && asdf local deno latest
      - run: echo ::set-output name=TO_VERSION::$(asdf current deno | xargs -n 1 | sed -n '2p')
        id: to
      - uses: maxkomarychev/octions/octions/repos/get-release-by-tag@master
        id: changelog
        with:
          token: ${{ github.token }}
          tag: ${{ steps.to.outputs.TO_VERSION }}
          custom_outputs: |
            body:body
      - uses: peter-evans/create-pull-request@v3.10.0
        with:
          title: "fix(deps): bump deno from ${{ steps.from.outputs.FROM_VERSION }} to ${{ steps.to.outputs.TO_VERSION }}"
          branch: dependencies/deno
          delete-branch: true
          labels: dependencies
          body: ${{ steps.changelog.body }}
