on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  updatedeno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: asdf-vm/actions/setup@v1.1.0
      - run: asdf plugin-add deno https://github.com/asdf-community/asdf-deno.git
      - run: asdf install deno latest
      - run: asdf local deno latest
      - run: git status
