on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  updatedeno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: asdf-vm/actions/setup@v1.1.0
      - run: asdf plugin-add deno https://github.com/asdf-community/asdf-deno.git
      - run: asdf current deno | xargs -n 1 | sed -n '2p'
      - id: from
        run: echo ::set-output name=FROM_VERSION::$(asdf current deno | xargs -n 1 | sed -n '2p')
      - run: asdf install deno latest && asdf local deno latest
      - id: to
        run: echo ::set-output name=TO_VERSION::$(asdf current deno | xargs -n 1 | sed -n '2p')
      - id: changelog
        uses: maxkomarychev/octions/octions/repos/get-release-by-tag@master
        with:
          token: ${{ github.token }}
          owner: denoland
          repo: deno
          tag: v${{ steps.to.outputs.TO_VERSION }}
          custom_outputs: |
            body:body
      - run: |
          echo "${{ steps.from.outputs.FROM_VERSION }}";
          echo "${{ steps.to.outputs.TO_VERSION }}";
          echo "${{ steps.changelog.outputs.body }}";
      #- uses: peter-evans/create-pull-request@v3.10.0
      #  with:
      #    title: "fix(deps): bump deno from ${{ steps.from.outputs.FROM_VERSION }} to ${{ steps.to.outputs.TO_VERSION }}"
      #    branch: dependencies/deno
      #    delete-branch: true
      #    labels: dependencies
      #    body: ${{ steps.changelog.outputs.body }}
