on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  CI: true

jobs:
  denolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
      - name: Get deno version
        run: echo ::set-output name=DENO_VERSION::$(cat .tool-versions | grep deno | xargs -n 1 | tail -n1)
        shell: bash
        id: denov
      - name: Install deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: ${{ steps.denov.outputs.DENO_VERSION }}
      - name: Check file format & style
        run: deno fmt --check --ignore="node_modules,deps.lock.json,CHANGELOG.md"
      - name: Lint JavaScript/TypeScript source code
        run: deno lint --ignore="node_modules,deps.lock.json,CHANGELOG.md"
