on: push

env:
  CI: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: "1.12.2"
      - run: deno test --allow-read --allow-write --allow-run --unstable
