on: push

env:
  CI: true

concurrency:
  group: "${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  test:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: asdf-vm/actions/install@v1.1.0
      - run: deno test --allow-read --allow-write --allow-run
