on: pull_request

env:
  CI: true

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4.1.1
        with:
          configFile: ./.commitlintrc.yml
          failOnWarnings: true
          firstParent: false

  denolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
      - name: Get deno version
        run: echo ::set-output name=DENO_VERSION::$(cat .tool-versions | grep deno | xargs -n 1 | tail -n1)
        shell: bash
        id: denov
      - name: Install deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: ${{ steps.denov.outputs.DENO_VERSION }}
      - name: Check file format & style
        run: deno fmt --check --ignore="node_modules,deps.lock.json,CHANGELOG.md"
      - name: Lint JavaScript/TypeScript source code
        run: deno lint --ignore="node_modules,deps.lock.json,CHANGELOG.md"

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
      - name: Get deno version
        run: echo ::set-output name=DENO_VERSION::$(cat .tool-versions | grep deno | xargs -n 1 | tail -n1)
        shell: bash
        id: denov
      - name: Install deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: ${{ steps.denov.outputs.DENO_VERSION }}
      - name: Restore deno cache
        uses: actions/cache@v2.1.6
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.lock.json') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            ~/.cache/deno/deps
            ~/Library/Caches/deno
            ~/AppData/Local/deno/deps
      - name: Execute deno tests
        run: deno test -A --unstable --lock deps.lock.json lib/
