on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

env:
  CI: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate as the denoexec bot
        id: generate_token
        uses: tibdex/github-app-token@v1.5.1
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_KEY }}

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Update all the things
        run: ./drake update

      - name: Create a PR with the updates
        uses: peter-evans/create-pull-request@v4.2.4
        with:
          title: "fix(deps): bump versions of all that we depend on"
          body: "Automated changes by https://github.com/peter-evans/create-pull-request"
          branch: dependencies/all-the-things
          delete-branch: true
          labels: dependencies
          token: ${{ steps.generate_token.outputs.token }}
